@isTest
public class InsertMSTZoneOpportunityTest
{
    @isTest
    public static void CreateOpportunityTestMethod()
    {
        //GL - DS - commented out so we can deploy code. The opp trigger is written wrong, and the test is failing because of it. 
       /* Opportunity objOpportunity = new Opportunity();
        objOpportunity.Name = 'Test Opp';
        objOpportunity.Type = 'New Business';
        objOpportunity.LeadSource = 'Email Marketing';
        objOpportunity.StageName = 'Closed Won';
        objOpportunity.CloseDate = Date.today().Adddays(5);
        insert objOpportunity;
        system.debug('id=' + objOpportunity.id);
        objOpportunity.Name='Test Opp Edited';
        update objOpportunity;*/
    }
}